services:
  abacus:
    build:
      context: ./abacus
      dockerfile: Dockerfile.abacus
    networks:
      - app-network
    ports:
      - "5000:5000"  # Adjust to the port your abacus service uses
    volumes:
      - ./abacus:/app
    # If you have environment variables, define them here. Otherwise, remove this section.
    # environment:
    #   VARIABLE_NAME: value

  calculator:
    build:
      context: ./calculator
      dockerfile: Dockerfile.calculator
    networks:
      - app-network
    ports:
      - "5001:5001"  # Adjust to the port your calculator service uses
    volumes:
      - ./calculator:/app
    # If you have environment variables, define them here. Otherwise, remove this section.
    # environment:
    #   VARIABLE_NAME: value

  app:
    build:
      context: ./main_app
      dockerfile: Dockerfile.app
    depends_on:
      - abacus
      - calculator
    volumes:
      - ./main_app:/app
    environment:
      ABACUS_HOST: abacus
      CALCULATOR_HOST: calculator
    networks:
      - app-network
    ports:
      - "8080:8080"

networks:
  app-network:
    driver: bridge
